<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>ToDo :)</title>
  <link href='http://fonts.googleapis.com/css?family=Bad+Script&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300&subset=latin,cyrillic,cyrillic-ext' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/styles.css?v=1">

  <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
</head>

<body>
  <div id="content"><?= $content ?></div>
  <script src="js/scripts.js"></script>
</body>
</html>